(define (problem Base)
	(:domain Planification)
	(:objects 	d0 d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 - day
		    	ex1 ex2 ex3 ex4 ex5 ex6 ex7  - exercice
				n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - nivell
	)
	 
	(:init
		(= (nivellO ex1) 1)
		(= (nivellF ex1) 1)
		(= (nivellO ex2) 1)
		(= (nivellF ex2) 1)
		(= (nivellO ex3) 1)
		(= (nivellF ex3) 1)
		(= (nivellO ex4) 1)
		(= (nivellF ex4) 1)
		(= (nivellO ex5) 1)
		(= (nivellF ex5) 1)
		(= (nivellO ex6) 1)
		(= (nivellF ex6) 8)
		(= (nivellO ex7) 1)
		(= (nivellF ex7) 7)

		(preparador ex1 ex6)
		(preparador ex2 ex6)
		(preparador ex3 ex6)
		(preparador ex4 ex6)
		(preparador ex5 ex6)

		(not(pendent ex1))
		(not(pendent ex2))
		(not(pendent ex3))
		(not(pendent ex4))
		(not(pendent ex5))
		(pendent ex6)
		(pendent ex7)


		(= (idDia d0) 0)
		(= (idDia d1) 1)
		(= (idDia d2) 2)
		(= (idDia d3) 3)
		(= (idDia d4) 4)
		(= (idDia d5) 5)
		(= (idDia d6) 6)
		(= (idDia d7) 7)
		(= (idDia d8) 8)
		(= (idDia d9) 9)
		(= (idDia d10) 10)
		(= (idDia d11) 11)
		(= (idDia d12) 12)
		(= (idDia d13) 13)
		(= (idDia d14) 14)
		(= (idDia d15) 15)
		(= (numExercicisDia d1) 0)
		(= (numExercicisDia d2) 0)
		(= (numExercicisDia d3) 0)
		(= (numExercicisDia d4) 0)
		(= (numExercicisDia d5) 0)
		(= (numExercicisDia d6) 0)
		(= (numExercicisDia d7) 0)
		(= (numExercicisDia d8) 0)
		(= (numExercicisDia d9) 0)
		(= (numExercicisDia d10) 0)
		(= (numExercicisDia d11) 0)
		(= (numExercicisDia d12) 0)
		(= (numExercicisDia d13) 0)
		(= (numExercicisDia d14) 0)
		(= (numExercicisDia d15) 0)

		(= (idNivell n1) 1)
		(= (idNivell n2) 2)
		(= (idNivell n3) 3)
		(= (idNivell n4) 4)
		(= (idNivell n5) 5)
		(= (idNivell n6) 6)
		(= (idNivell n7) 7)
		(= (idNivell n8) 8)
		(= (idNivell n9) 9)
		(= (idNivell n10) 10)

	)
	(:goal
    (forall (?ex - exercice) (not (pendent ?ex))
	)
  )
)